replicaCount: 1

image:
  repository: 713923090919.dkr.ecr.us-east-1.amazonaws.com/taskflow-backstage
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 7007

existingSecret: backstage-secrets

rdsCa:
  configMapName: rds-ca-bundle
  fileName: rds-ca-us-east-1.pem
  mountPath: /etc/ssl/rds

postgres:
  host: taskflow-backstage.ce54ui0w20kx.us-east-1.rds.amazonaws.com
  port: "5432"
  user: backstage_admin

probes:
  readinessPath: /.backstage/health/v1/readiness
  livenessPath: /.backstage/health/v1/liveness 

backstage:
  baseUrl: http://localhost:7007

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi